name: clean_template
description: A CLI tool to bootstrap a clean architecture for your Dart and Flutter projects.
version: 1.0.2
repository: https://github.com/csezoli21/clean_template
homepage: https://github.com/csezoli21/clean_template
license: MIT
funding:
  - https://buymeacoffee.com/csezoli
topics:
  - clean-architecture
  - cli
  - codegen
  - flutter
  - dart

environment:
  sdk: '>=3.5.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

executables:
  clean_template:

dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
